package metrics

import (
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	generatedRequestsTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "exchange_generator_requests_total",
		Help: "Total number of bid requests generated by the load generator.",
	})

	clientRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "exchange_client_requests_total",
			Help: "Total number of outbound client requests grouped by normalized result.",
		},
		[]string{"status", "http_status", "http_status_class"},
	)

	clientRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "exchange_client_request_duration_seconds",
			Help:    "Latency of outbound client requests.",
			Buckets: []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5},
		},
		[]string{"status"},
	)

	clientRequestsInFlight = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "exchange_client_requests_in_flight",
		Help: "Current number of outbound client requests in progress.",
	})
)

func init() {
	prometheus.MustRegister(
		generatedRequestsTotal,
		clientRequestsTotal,
		clientRequestDuration,
		clientRequestsInFlight,
	)
}

func IncGeneratedRequest() {
	generatedRequestsTotal.Inc()
}

func IncInFlight() {
	clientRequestsInFlight.Inc()
}

func DecInFlight() {
	clientRequestsInFlight.Dec()
}

func ObserveClientRequest(status string, httpStatus int, latency time.Duration) {
	httpStatusLabel, httpStatusClass := statusLabels(httpStatus)

	clientRequestsTotal.WithLabelValues(status, httpStatusLabel, httpStatusClass).Inc()
	clientRequestDuration.WithLabelValues(status).Observe(latency.Seconds())
}

func Handler() http.Handler {
	return promhttp.Handler()
}

func statusLabels(httpStatus int) (string, string) {
	if httpStatus == 0 {
		return "none", "none"
	}

	return strconv.Itoa(httpStatus), strconv.Itoa(httpStatus/100) + "xx"
}
